name: TrHologram
main: me.arasple.mc.trhologram.TrHologram

api-version: 1.13
version: ${version}

softdepend:
  - PlaceholderAPI
  - HolographicDisplays

built-time: ${built}

description: Powerful advanced dynamic hologram