name: ${name}
main: ${main}

author: Arasple

api-version: 1.13
version: ${version}

lib-version: ${libVersion}
lib-download: ${libDownload}
loader-version: ${loaderVersion}

github: https://github.com/Arasple/${name}
description: Modern & Advanced Hologram-Plugin for Minecraft Servers

softdepend: [ PlaceholderAPI ]

built-time: ${built}
built-by: ${builder}
built-os: ${os}