# 不要更改
CONFIG-VERSION: 1

# 本地语言加载顺序
LOCALE-PRIORITY:
  - zh_CN
  - en_US

# 选项
OPTIONS:
  # 自动重载是否播放音效
  AUTO-RELOAD-SOUND: true
  # 每行全息图的盔甲架高度距离
  ARMORSTAND-DISTANCE: 0.25
  # 是否使用小盔甲架 (非特殊情况不要关)
  ARMORSTAND-SMALL: true

# 菜单自定义显示物品
GUIS:
  EDITOR:
    BOOK:
      name: '&7「 &b编辑全息图 &8[{0}] &7」'
      lore:
        - ''
        - '&7左键交互方块点击打开管理 GUI'
        - '&7右键点击快捷编辑内容'
        - ''
    CONTENTS:
      material: WRITABLE_BOOK
      name: '&b✏ &3编辑内容'
      lore:
        - ''
        - '&7点击此处获取一本书,'
        - '&7你可以用其轻松编辑全息图!'
        - ''
    MOVE:
      material: ENDER_PEARL
      name: '&a◉ &2移动位置'
      lore:
        - ''
        - '&7点击移动该全息图到你当前的位置'
        - ''
    DELETE:
      material: LAVA_BUCKET
      name: '&c◆ &4删除'
      lore:
        - ''
        - '&8[&6&l!&8] &c该操作不可逆，永久删除'
        - '&7点击即可删除该全息图'
        - ''